version: "3.9"
services:
  fastapi:
    build: .
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - "${FILESYSTEM}:/filesystem"
    ports:
      - "8000:8000"